# 2_model_representation

In [1]:
import numpy as np

In [2]:
weight_vector = np.array([[1],[1],[1]])
x_vector = np.array([[3],[4],[5]])

In [3]:
weight_vector.T.dot(x_vector)

array([[12]])

In [4]:
import pandas as pd

In [5]:
data_url = 'data/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [6]:
df_data['weight_0'] = 1
df_data= df_data.drop("MEDV", axis =1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [7]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14,1))

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [8]:
df_matrix.dot(weight_vector)

array([[250.62900892],
       [228.72492335],
       [217.53469665],
       [203.22275018],
       [208.8062923 ],
       [209.86698212],
       [259.39712738],
       [276.87342282],
       [282.62361207],
       [269.61568503],
       [276.35773446],
       [267.78111438],
       [247.92131406],
       [247.855391  ],
       [255.81936221],
       [245.19353097],
       [230.5432231 ],
       [258.17900228],
       [217.64237745],
       [251.1994511 ],
       [266.74571163],
       [261.95815115],
       [266.78921175],
       [270.55906428],
       [266.07563874],
       [245.35896226],
       [260.39405975],
       [247.95941339],
       [263.34420715],
       [258.27912819],
       [263.11906483],
       [263.603712  ],
       [236.78486564],
       [260.56483698],
       [242.13314403],
       [238.15092696],
       [232.46804198],
       [226.11607633],
       [221.23937659],
       [266.90028557],
       [263.11633674],
       [188.04998635],
       [189.57652908],
       [192

In [9]:
df_data.values.dot(weight_vector)

array([[250.62900892],
       [228.72492335],
       [217.53469665],
       [203.22275018],
       [208.8062923 ],
       [209.86698212],
       [259.39712738],
       [276.87342282],
       [282.62361207],
       [269.61568503],
       [276.35773446],
       [267.78111438],
       [247.92131406],
       [247.855391  ],
       [255.81936221],
       [245.19353097],
       [230.5432231 ],
       [258.17900228],
       [217.64237745],
       [251.1994511 ],
       [266.74571163],
       [261.95815115],
       [266.78921175],
       [270.55906428],
       [266.07563874],
       [245.35896226],
       [260.39405975],
       [247.95941339],
       [263.34420715],
       [258.27912819],
       [263.11906483],
       [263.603712  ],
       [236.78486564],
       [260.56483698],
       [242.13314403],
       [238.15092696],
       [232.46804198],
       [226.11607633],
       [221.23937659],
       [266.90028557],
       [263.11633674],
       [188.04998635],
       [189.57652908],
       [192